version: 2.1

jobs:
  build:
    docker:
     - image: cimg/node:18.11.0
    
    steps:
      - checkout
      - run:
           name: "Setup custom environment variables"
           command: echo 'export CUSTOM_ENV_VAR="FOO"' >> "$BASH_ENV"


      - run:
            name: "Print an env var stored in the Project"
            command: echo ${PROJECT_ENV_VAR}

      - run:
            name: "Print an env var stored in a Context"
            command: echo ${CONTEXT_ENV_VAR}

      - run:
            name: "Print custom environment variable"
            command: echo ${CUSTOM_ENV_VAR}

workflows:
  build:
    jobs:
      - build:
          context: Custom-context                        
